
spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/thewine-db
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: create
          show-sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect



springdoc:
   swagger-ui:
     path: /swagger-ui.html

server:
  error:
    include-stacktrace: never