
spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/thewine-db}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:password}
    jpa:
        hibernate:
          ddl-auto: create
          show-sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

   # flyway:
       # enabled: true
       # locations: classpath:db/migration

springdoc:
   swagger-ui:
     path: /swagger-ui.html

server:
  error:
    include-stacktrace: never

api:
  issuer:
    name: ${ISSUER_NAME:thewine-api}
  security:
    jwt:
      secret: ${JWT_SECRET:secret}
      expiration: ${JWT_EXPIRATION:86400000}
