logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG


spring:
    datasource:
        url: jdbc:h2:mem:thewinedb
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
          ddl-auto: ${DB_DDL-AUTO:none}
          show-sql: true
          dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

    h2:
        console:
          enabled: true
          path: /h2-console

    flyway:
        enabled: true
        locations: classpath:db/migration

springdoc:
   swagger-ui:
     path: /swagger-ui.html

server:
  error:
    include-stacktrace: never

api:
  issuer:
    name: ${ISSUER_NAME:thewine-api}
  security:
    jwt:
      secret: ${JWT_SECRET:secret}
      expiration: ${JWT_EXPIRATION:86400000}
